### ISSUE TITLE
Using MonaServer to ffmpeg

### ISSUE THREAD

**Issue by Slyke** [MonaSolutions/MonaServer#90]
I'm trying to use OBS to stream to MonaServer, and then to ffmpeg so that it can tee the streams to Youtube and Twitch.

Here is my Docker Compose file:
```
version: '3.6'
services:
  monaserver:
    image: monaserver/monaserver
    container_name: monaserver
    ports:
    - "1935:1935"
    - "1935:1935/udp"
    - "554:554"
    restart: unless-stopped
    networks:
    - broadcaster_nw
  ffmpeg:
    image: jrottenberg/ffmpeg
    container_name: ffmpeg
    depends_on:
      - "monaserver"
    restart: unless-stopped
    command: 'ffmpeg -i rtmp://monaserver:1935/live/stream -c:v copy -c:a copy -map 0 -f tee "[f=flv]rtmp://a.rtmp.youtube.com/live2/XXXX-XXXX-XXXX-XXXX|[f=flv]rtmp://live-sea.twitch.tv/app/live_XXXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXX"'
    networks:
    - broadcaster_nw

networks:
  broadcaster_nw:
    name: BroadcasterNetwork
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.77.61.0/24
```

This is the error ffmpeg gives:
```
ffmpeg        | ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
ffmpeg        |   built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 20160609
ffmpeg        |   configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3 --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
ffmpeg        |   libavutil      56. 22.100 / 56. 22.100
ffmpeg        |   libavcodec     58. 35.100 / 58. 35.100
ffmpeg        |   libavformat    58. 20.100 / 58. 20.100
ffmpeg        |   libavdevice    58.  5.100 / 58.  5.100
ffmpeg        |   libavfilter     7. 40.101 /  7. 40.101
ffmpeg        |   libavresample   4.  0.  0 /  4.  0.  0
ffmpeg        |   libswscale      5.  3.100 /  5.  3.100
ffmpeg        |   libswresample   3.  3.100 /  3.  3.100
ffmpeg        |   libpostproc    55.  3.100 / 55.  3.100
ffmpeg        | [rtmp @ 0xc57a00] Unknown connect error (unsupported authentication method?)
ffmpeg        | [rtmp @ 0xc57a00] Server error: Application /live doesn't exist
ffmpeg        | rtmp://monaserver:1935/live/stream: Unknown error occurred
```

Here are the logs from MonaServer:
```
docker exec monaserver tail -f /usr/local/bin/MonaServer.log/0.log
07/08 07:58:27.1  ERROR  7 MonaServer.cpp[154]              Application /live doesn't exist
07/08 07:58:27.1  WARN   7 TCPSession.cpp[32]               RTMP 1-10.77.61.3:48770, Connection reseted
07/08 07:58:27.8  DEBUG  7 Sessions.cpp[124]                RTMP 1-10.77.61.3:48770 deleted (client.id=59c4215a0ba0b767f1e07e8234cd7b8d7dfceab4d875dc0279f92c3eb6b6b692)
07/08 07:58:27.8  DEBUG  7 FlashStream.cpp[36]              FlashStream id=0 deleted
07/08 07:58:33.8  DEBUG  7 FlashStream.cpp[31]              FlashStream 0 created
07/08 07:58:33.8  DEBUG  7 Sessions.h[85]                   RTMP 2-10.77.61.3:48822 created (client.id=e13748cdb70242b1c83c2857ed0ebe57b26a3adcd673a42eacf5fc5ffee117df)
07/08 07:58:33.8  ERROR  7 MonaServer.cpp[154]              Application /live doesn't exist
07/08 07:58:33.8  WARN   7 TCPSession.cpp[32]               RTMP 2-10.77.61.3:48822, Connection reseted
07/08 07:58:35.8  DEBUG  7 Sessions.cpp[124]                RTMP 2-10.77.61.3:48822 deleted (client.id=e13748cdb70242b1c83c2857ed0ebe57b26a3adcd673a42eacf5fc5ffee117df)
07/08 07:58:35.8  DEBUG  7 FlashStream.cpp[36]              FlashStream id=0 deleted
07/08 07:58:47.0  DEBUG  7 FlashStream.cpp[31]              FlashStream 0 created
```
